app/main/forms.py
#-*- coding=utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Required, length, Regexp


class AddComRecordForm(FlaskForm):
    """
    用户提交维修记录的表单
    """
    user = StringField(u'* 物主姓名:', validators=[Required(), length(2, 6, message=u'姓名只允许2-6个字符！')])
    phone = StringField(u'* 手机号:', validators=[Required(), length(6, 11, message=u'只允许6-11位数字'), Regexp('[0-9]')])
    problem = TextAreaField(u'* 简要描述您的问题:', validators=[Required()])
    computer_type = StringField(u'* 您的电脑型号:', validators=[Required()])
    computer_password = StringField(u'您的电脑密码（可不填）:')
    submit = SubmitField(u'提交')

class AddEleRecordForm(FlaskForm):
    """
    用户提交维修记录的表单
    """
    user = StringField(u'* 物主姓名:', validators=[Required(), length(2, 5, message=u'姓名只允许2-5个字符！')])
    phone = StringField(u'* 手机号:', validators=[Required(), length(6, 11, message=u'只允许6-11位数字'), Regexp('[0-9]')])
    problem = TextAreaField(u'* 简要描述您的问题:', validators=[Required()])
    ele_type = StringField(u'* 您的电器类型:', validators=[Required()])
    submit = SubmitField(u'提交')


class GetRandomIdForm(FlaskForm):
    """
    序号相关的表单
    """
    random_id = StringField(u'请输入您的序列号：', validators=[Required()])
    submit = SubmitField(u'确认取回')

class PostInquire(FlaskForm):
    random_id = StringField(u'请输入您的序列号：', validators=[Required()])
    submit = SubmitField(u'维修进度查询')

class AddCommentForm(FlaskForm):

    comment = TextAreaField(u'* 填写你的表白:', validators=[Required(),length(1, 64)])
    submit = SubmitField(u'提交')

app/main/__init__.py
# -*- coding=utf-8 -*-
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
#-*- coding=utf-8 -*-
from flask import render_template, flash, redirect, url_for, request
from . import main
from .forms import AddCommentForm,AddComRecordForm, GetRandomIdForm,AddEleRecordForm,PostInquire
from ..models import Record,Erecord,Unid,Comment,Article,Category
from .. import db
from datetime import datetime
import random
import string


@main.route('/')
def index():
    '''
    clist = Category.query.all()
    alist = Article.query.all()
    return render_template('main/index.html',clist=clist,alist=alist)
    '''
    return redirect(url_for('main.user_amend'))

@main.route('/test')
def test():
    return render_template('main/front.html')


@main.route('/.well-known/pki-validation/fileauth.txt')
def tencentssl():
    return '201712101454112neoivuld5m1usydql34l0sudhgrsq8g6hmmqxko2xs3nvkuxh'

@main.route('/user/amend', methods=['GET', 'POST'])
def user_amend():
    """
    用户添加维修记录
    :return:
    """
    dayOfWeek = datetime.today().weekday()
    type = request.args.get('type')
    if type == '2':
        form = AddEleRecordForm()
    else:
        form = AddComRecordForm()
    # alist = Record.query.all()
    if form.validate_on_submit():
        unid = Unid(random_id = string.join(
            random.sample(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], 5)).replace(' ', ''))
        try:
            db.session.add(unid)
            db.session.commit()
        except:
            db.session.rollback()
            flash(u'随机码生成失败')
        if type == '2':
            erecord = Erecord(user=form.user.data, phone=form.phone.data, problem=form.problem.data,
                              create_time=datetime.now(), ele_type=form.ele_type.data, random_id=unid.random_id)
        else:
            record = Record(user=form.user.data, phone=form.phone.data, problem=form.problem.data,
                            create_time=datetime.now(),
                            computer_type=form.computer_type.data, computer_password=form.computer_password.data,
                            random_id=unid.random_id)
        i = 1
        while(i):
            try:
                if type == '2':
                    db.session.add(erecord)
                    db.session.commit()
                    flash(u'记录添加成功,您的随机码是 %s, 请务必截图保存' % erecord.random_id)
                else:
                    db.session.add(record)
                    db.session.commit()
                    flash(u'记录添加成功,您的随机码是 %s, 请务必截图保存' % record.random_id)
                i = 0
                return redirect(url_for('main.user_verify', random_id=unid.random_id))
            except:
                db.session.rollback()
    return render_template('main/amend.html', form=form)


@main.route('/user/verify/<int:random_id>', methods=['GET', 'POST'])
def user_verify(random_id):
    """
    用户确认物品取回
    :return:
    """
    form = GetRandomIdForm(random_id=random_id)
    if form.validate_on_submit():
        random_id = form.random_id.data
        record = Record.query.filter(Record.random_id == random_id).first()
        if record is None:
            erecord = Erecord.query.filter(Erecord.random_id == random_id).first()
            erecord.verify = True
            db.session.add(erecord)
            db.session.commit()
            flash(u'已确认取回')
        else:
            try:
                record.verify = True
                db.session.add(record)
                db.session.commit()
                flash(u'已确认取回')
            except:
                db.session.rollback()
                flash(u'未知错误')
        return redirect(url_for('main.user_amend'))
    return render_template('main/verify.html', form=form)


@main.route('/user/verify', methods=['GET', 'POST'])
def user_Verify():
    """
    用户确认物品取回
    :return:
    """
    form = GetRandomIdForm()
    if form.validate_on_submit():
        random_id = form.random_id.data
        record = Record.query.filter(Record.random_id == random_id).first()
        if record is None:
            erecord = Erecord.query.filter(Erecord.random_id == random_id).first()
            erecord.verify = True
            db.session.add(erecord)
            db.session.commit()
            flash(u'已确认取回')
        else:
            try:
                record.verify = True
                db.session.add(record)
                db.session.commit()
                flash(u'已确认取回')
            except:
                db.session.rollback()
                flash(u'未知错误')
        return redirect(url_for('main.user_amend'))
    return render_template('main/verify.html', form=form)

@main.route('/comment', methods=['GET', 'POST'])
def comment():
    form = AddCommentForm()
    if form.validate_on_submit():
        comment = Comment(comment = form.comment.data,create_time=datetime.now())
        i = 1
        while(i):
            try:
                db.session.add(comment)
                db.session.commit()
                flash(u'评论提交成功')
                i = 0
                return redirect(url_for('main.index'))
            except:
                db.session.rollback()
    return render_template('main/comment.html', form=form)

@main.route('/read/', methods=['GET'])
def read():
    a = Article.query.filter_by(id=request.args.get('id')).first()
    if a is not None:
        return render_template('main/read.html', a=a)
    flash(u'未找到相关文章')
    return redirect(url_for('main.index'))


@main.route('/user/inquire/', methods=['GET', 'POST'])
def inquire():
    form = PostInquire()
    if form.validate_on_submit():
        random_id = form.random_id.data
        record = Record.query.filter(Record.random_id == random_id).first()
        if record is None:
            record = Erecord.query.filter(Erecord.random_id == random_id).first()
        if record is None:
            flash(u'登记码错误')
        else:
            status = record.solve
            return render_template('main/inquire.html', form=form, status=status)
    return render_template('main/inquire.html', form=form)


app/templates/main/amend.html
{% extends "main/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <div class="col-md-6">
        <h1>维修登记</h1>
        <hr>
        <div class="btn-group btn-group-lg" role="group" aria-label="...">
            <a href="{{ url_for('main.user_amend', type=1) }}" button type="button" class="btn btn-default btn-lg" >我要修电脑</a></button>
            <a href="{{ url_for('main.user_amend', type=2) }}" button type="button" class="btn btn-default btn-lg">我要修电器</a></button>
        </div>
        <br>
        <br>
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/templates/main/base.html
{% extends "bootstrap/base.html" %}
{% block title %}E志者维修登记平台{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.ico') }}"
type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}"
type="image/x-icon">
<script  src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
    <style type="text/css">
		.scrollspy-example {
			height: 900px;
			overflow: auto;
			position: relative;
		}
	</style>
{% endblock %}


{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">浙江大学学生E志者协会</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/user/amend">我要维修</a></li>
                <li><a href="/user/verify">确认取回</a></li>
                <li><a href="/user/inquire">维修进度查询</a></li>
{#                <li><a href="{{ url_for('main.comment') }}">表白墙</a></li>#}
            </ul>
            <ul class="nav navbar-nav navbar-right">
{#                <li><a href="{{ url_for('admin.register') }}">注册</a></li>#}
                <li><a href="{{ url_for('admin.index') }}">管理员</a></li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
        {% block page_content %}{% endblock %}
    </div>
    <div class="footer">
        <ul class="list-inline text-center">
            <hr />
            <li>浙江大学东三-200 <strong><a href="//zjueva.cn/" >浙江大学学生E志者协会</a></strong></li>
                <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1270698442'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s22.cnzz.com/z_stat.php%3Fid%3D1270698442%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));</script>
                <p>备案号：浙ICP备17008331号</p>
        </ul>
    </div>
{% endblock %}


app/templates/main/comment.html
{% extends "main/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <div class="col-md-6">
        <h1>表白提交</h1>
        <hr>
        {{ wtf.quick_form(form) }}
    </div>
    <div class="col-md-6">
    </div>
{% endblock %}

app/templates/main/front.html
{% extends "bootstrap/base.html" %}
{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.ico') }}"
type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}"
type="image/x-icon">
<script  src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
{% endblock %}
{% block content %}
<script type=text/javascript>
      $(document).ready(function(){
          $('#myModal').modal('show')
        });
</script>
<style type="text/css">
        body {
            background-color: red;
        }
	</style>
<div class="modal" tabindex="-1" role="dialog" id="myModal" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <h3><strong>登记时不要忘记检查是否拆机、是否解决和是否取回的选项</strong></h3>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}

app/templates/main/id.html
{% extends "main/base.html" %}

{% block page_content %}
<div class="container">
    <div class="page-header">
        <li><p>你的序列号是</p>{{ id }}</li>
        <li>请注意截图保存</li>
    </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends "main/base.html" %}

{% block content %}
<!--img src="{{ url_for('static', filename = 'main/backgroud.png') }}" alt="First slide"-->
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1503216871488&di=481fd3b30c4b7251954206a7c35b6453&imgtype=jpg&src=http%3A%2F%2Fimg1.imgtn.bdimg.com%2Fit%2Fu%3D321143402%2C194363490%26fm%3D214%26gp%3D0.jpg" alt="First slide" alt="...">
              <div class="carousel-caption">
                1
              </div>
            </div>
            <div class="item">
              <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1503216918747&di=f9218ac8950dd99eb120215173bcd31a&imgtype=0&src=http%3A%2F%2Fs9.knowsky.com%2Fbizhi%2Fl%2F5001-10000%2F2009528111954303053199.jpg" alt="...">
              <div class="carousel-caption">
                2
              </div>
            </div>
              <div class="item">
                <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1503216960910&di=b60386ac6d97306c96a965031325cc7e&imgtype=0&src=http%3A%2F%2Fs9.knowsky.com%2Fbizhi%2Fl%2F5001-10000%2F2009528111948265553116.jpg" alt="...">
                <div class="carousel-caption">
                  3
              </div>
              </div>
                 <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
        </div>
        </div>
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-md-10">
      <nav id="navbar-example" class="navbar navbar-default navbar-static" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse"
                        data-target=".bs-js-navbar-scrollspy">
                    <span class="sr-only">切换导航</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">教程名称</a>
            </div>
            <div class="collapse navbar-collapse bs-js-navbar-scrollspy">
                <ul class="nav navbar-nav">
                    <li><a href="#video">社团视频</a></li>
                    <li><a href="#introduction">社团简介</a></li>
                    <li><a href="#history">我们的历史</a></li>
                </ul>
            </div>
        </div>
    </nav>
<div class="text-center" data-spy="scroll" data-target="#navbar-example" data-offset="0"
	 style="overflow:auto; position: relative;">
	<h1 id="video">社团视频</h1>
  <br>
	<div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="http://v.qq.com/iframe/player.html?vid=g01655y5lkz"></iframe>
    </div>
  <br><br><br>

    <h1 id="introduction">社团简介</h1>
  <br>
	<p style="font-size:x-large">
      E志者协会以“奉献爱心、服务群众”为己任，凝聚拥有电器维修爱好者的力量，以电气学院丰富的学科优势资源为依托，提供浙大学子展示自我、服务大众的平台，建设提高专业知识、交流技术经验的环境，全面提高会员的综合素质，近年来更是实现了由老的志愿者服务组织向新的社团组织发展的成功转型。E志者协会及其前身电气维修小组多次被评为校级志愿者先进（优秀）集体，还曾获得“浙江大学十大优秀志愿者服务集体”、“浙江省优秀志愿者服务队伍”。2006年，其便民利民服务项目被评为“省级青年志愿者服务工程”。2007年被列为“浙江大学大学生素质拓展基地创建单位”
	</p>
  <br><br><br>

	<h1 id="history">我们的历史</h1>
  <br>
	<p style="font-size:x-large">浙江大学学生E志者协会的前身是<br><br>
      1984年前电机系（现电气工程学院）的<br><br>
      学生（陈强等）创办的<br><br>
      <strong>电器维修小组</strong><br><br>
      在2008年9月正式成为校级学生社团<br><br>
      <img class="center block" src="{{ url_for('static', filename = 'main/history.jpg') }}" alt="history">
	</p>
</div>
    </div>
    <div class="col-xs-2 col-md-2">
        <br><br><br><br><br><br><br><br><br><br><br><br><br>
        <div class="panel panel-default">
          <div class="panel-heading">目录</div>
              <ul class="list-group">
                {% for foo in clist %}
                <a href="#" class="list-group-item">{{ foo.name }}</a>
                {% endfor %}
              </ul>
        </div>
        <br><br><br><br><br><br><br><br><br><br><br><br><br>
        <div class="panel panel-default">
          <div class="panel-heading">近期文章</div>
                <ul class="list-group">
                {% for foo in alist %}
                    <a href="{{ url_for('main.read' , id=foo.id) }}" class="list-group-item">{{ foo.title }}     {{ foo.create_time }}</a>
                {% endfor %}
                </ul>
        </div>
    </div>
  </div>
</div>
    <div class="footer">
        <ul class="list-inline text-center">
            <hr />
            <li>浙江大学东三-200 <strong><a href="//zjueva.cn/" >浙江大学学生E志者协会</a></strong>
                备案号：浙ICP备17008331号</li>
        </ul>
    </div>
{% endblock %}

app/templates/main/inquire.html
{% extends "main/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<h1>维修进度查询</h1>
<div class="col-md-6">
        <hr>
        {{ wtf.quick_form(form) }}
    </div>
    <div class="col-md-6">
            {% if (status==True) %}
            <h2>维修已完成，请选择空闲时间到东三200取回</h2>
            {% elif (status==False) %}
            <h2>维修还在进行中，请耐心等待</h2>
            {% endif %}
    </div>
{% endblock %}

app/templates/main/read.html
{% extends 'main/base.html' %}
{% block page_content %}
<div class="page-header">
    <h2>{{ a.title }}</h2>
            <hr>
            <p>{{ a.create_time }} | {{ a.category.name }}</p>
        {% if a.body_html %}
            {{ a.body_html | safe }}
        {% else %}
            {{ a.body }}
        {% endif %}
</div>
{% endblock %}

app/templates/main/verify.html
{% extends "main/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="col-md-6">
        <h1>取回确认</h1>
        <p style="color:red">当您取回电脑或电器并离开时，请确认取回</p>
        <hr>
        {{ wtf.quick_form(form) }}
    </div>
    <div class="col-md-6">
    </div>
{% endblock %}